services:
  webapp:
    build:
      context: ./WebApp
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8765:8765"
    environment:
      - MONGO_URI=mongodb://db:27017/iot  # Usa il nome del servizio db
    depends_on:
      - db

  db:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

